# Generated by Django 4.0.5 on 2022-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
