# Generated by Django 4.0.5 on 2022-07-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_activities_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
